version: '2.1'

services:
  project-database:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: DataBase
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - database-data:/var/lib/mysql

  account:
    build:
      context: ./
      dockerfile: account/Dockerfile
    container_name: Account
    environment:
      - DB_HOST=DataBase
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      project-database:
        condition: service_healthy

  catalog:
    build:
      context: ./
      dockerfile: catalog/Dockerfile
    container_name: Catalog
    environment:
      - DB_HOST=DataBase
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8081:8081
    networks:
      - arch-network
    depends_on:
      project-database:
        condition: service_healthy

  cart:
    build:
      context: ./
      dockerfile: cart/Dockerfile
    container_name: Cart
    environment:
      - SERVICE_HOST=account
      - DB_HOST=DataBase
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8082:8082
    networks:
      - arch-network
    depends_on:
      project-database:
        condition: service_healthy
      account:
        condition: service_started
      catalog:
        condition: service_started

volumes:
  database-data:

networks:
  arch-network:
    driver: "bridge"
    external: false